//
// Created by zixin on 7/8/22.
//

#ifndef VILEOM_WLKINEMATICS_H
#define VILEOM_WLKINEMATICS_H

#include <eigen3/Eigen/Dense>

class WLKinematics {

    public:
        WLKinematics() = default;
        ~WLKinematics() = default;

        // rho opt are contact offset cx cy cz
        // rho fix are body offset x & y, thigh offset, upper leg length, lower leg length
        // functions with eigen interface
        // forward kinematics 3x1
        Eigen::Vector3d fk(Eigen::Vector3d q, Eigen::VectorXd rho_fix);
        // jacobian 3x3
        Eigen::Matrix3d jac(Eigen::Vector3d q, Eigen::VectorXd rho_fix);    
    private:
        // functions with basic C++ interface, generated by Matlab
        void autoFunc_fk_derive(const double theta[3], const double rho_fix[5], double foot_pos[3]);
        void autoFunc_d_fk_dtheta(const double theta[3], const double rho_fix[5], double jacobian[9]);
};


#endif //VILEOM_WLKINEMATICS_H
